// This file is auto-generated by @hey-api/openapi-ts

export type Body_documents_upload_document = {
    file: (Blob | File);
    title?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DocumentPublic = {
    title: string;
    content: string;
    id: string;
    accuracy_report?: (string | null);
    is_accurate?: (boolean | null);
    created_at: string;
    owner_id: string;
};

export type DocumentsPublic = {
    data: Array<DocumentPublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type TenantCreate = {
    id: string;
    name: string;
    db_uri: string;
    is_active?: boolean;
};

export type TenantPublic = {
    id: string;
    name: string;
    db_uri: string;
    is_active?: boolean;
};

export type TenantUpdate = {
    name?: (string | null);
    db_uri?: (string | null);
    is_active?: (boolean | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type DocumentsUploadDocumentData = {
    formData: Body_documents_upload_document;
};

export type DocumentsUploadDocumentResponse = (DocumentPublic);

export type DocumentsReadDocumentsData = {
    limit?: number;
    skip?: number;
};

export type DocumentsReadDocumentsResponse = (DocumentsPublic);

export type DocumentsReadDocumentByIdData = {
    docId: string;
};

export type DocumentsReadDocumentByIdResponse = (DocumentPublic);

export type DocumentsDeleteDocumentData = {
    docId: string;
};

export type DocumentsDeleteDocumentResponse = (Message);

export type DocumentsChatAboutDocumentData = {
    docId: string;
    requestBody: {
        [key: string]: (string);
    };
};

export type DocumentsChatAboutDocumentResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TenantsCreateTenantData = {
    requestBody: TenantCreate;
};

export type TenantsCreateTenantResponse = (TenantPublic);

export type TenantsReadTenantsData = {
    limit?: number;
    skip?: number;
};

export type TenantsReadTenantsResponse = (Array<TenantPublic>);

export type TenantsReadTenantByIdData = {
    tenantId: string;
};

export type TenantsReadTenantByIdResponse = (TenantPublic);

export type TenantsUpdateTenantData = {
    requestBody: TenantUpdate;
    tenantId: string;
};

export type TenantsUpdateTenantResponse = (TenantPublic);

export type TenantsDeleteTenantData = {
    tenantId: string;
};

export type TenantsDeleteTenantResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);